### ISSUE TITLE
How do I make 2 figures exactly the same size?

### ISSUE THREAD

**Issue by them0llusk** [pedro-callil/tikzviolinplots#2]
I am using this package to make many violin plots in seperate files using tikz externalization locally, and then uploading the figures to my main document on overleaf. **My problem is that I really cannot figure out how to force the figures to have the same size along with a font size that matches the font size in the main document.**

I have an unsolved question on stack exchange with more detail: https://tex.stackexchange.com/questions/697073/externalizing-figures-from-tikzviolinplots-package-in-consistent-size?noredirect=1#comment1731438_697073

Using something like the following before \begin{figure}
`		\pgfplotsset{compat=newest,width=7cm, height=6cm}`

seems to be very hit or miss. 

What am I missing?

**Comment by pedro-callil** [comment]
If you have the same problem as the question linked in your question, it can be solved in the same way. As all options related to axis, labels, ticks, _etc_., `ylabel style` can be set through `\violinsetoptions`. Hence, with a small modification to your example, below, the problem seems to be fixed (_cf._ attached image).


```tex
\begin{tikzpicture}
    \violinsetoptions[
        averages,
        data points,
        scaled
    ]{
        xmin=0,xmax=4,
        ymin=-0.5,ymax=1,
        ylabel style={
            at={(rel axis cs:-0.1,0.5)}
        },
        ymajorgrids=true,
        ylabel={ylabel text},
    }
...
``` 

![example after this modification](https://github.com/pedro-callil/tikzviolinplots/assets/82470941/e27ae833-dd71-4b04-8291-2329740d04fe)
